src/Kawaz/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

# Include Application
#--------------------------------------------------------------------------------
urlpatterns = patterns('',
    # Admin site
    (r'^central-dogma/doc/',                    include('django.contrib.admindocs.urls')),
    (r'^central-dogma/',                        include(admin.site.urls)),
    # Contrib
    (r'^comments/',                             include('Kawaz.mcomments.urls')),
    (r'^search/',                               include('haystack.urls')),
    # Applications
    (r'^trackback/',                            include('libwaz.contrib.trackback.urls')),
    (r'^drafts/',                               include('libwaz.contrib.drafts.urls')),
    (r'^permissiongroups/',                     include('Kawaz.permissiongroups.urls')),
    (r'^registration/',                         include('Kawaz.threestep_registration.urls')),
    (r'^history/',                              include('libwaz.contrib.history.urls')),
    (r'^commons/',                              include('Kawaz.commons.urls')),
    (r'^events/',                               include('Kawaz.events.urls')),
    (r'^tweets/',                               include('Kawaz.tweets.urls')),
    (r'^threads/',                              include('Kawaz.threads.urls')),
    (r'^messages/',                             include('Kawaz.messages.urls')),
    (r'^tasks/',                                include('Kawaz.tasks.urls')),
    (r'^projects/',                             include('Kawaz.projects.urls')),
    (r'^projects/(?P<project>[^/]+)/wikis/',    include('Kawaz.wikis.urls')),
    (r'^announcements/',                        include('Kawaz.announcements.urls')),
    (r'^tags/',                                 include('libwaz.contrib.tagging.urls')),
    (r'^',                                      include('Kawaz.index.urls')),
    (r'^members/',                              include('Kawaz.profiles.urls')),
    (r'^blogs/',                                include('Kawaz.blogs.urls')),
    (r'^bugwaz/',                               include('Kawaz.bugwaz.urls')),
    (r'^utilities/',                            include('Kawaz.utilities.urls')),
    (r'^contact/',                              include('Kawaz.contact.urls')),
    (r'^calls/',                                include('libwaz.contrib.calls.urls')),
    (r'^star/',                                 include('libwaz.contrib.star.api.urls')),
    (r'^adam/',                                 include('Kawaz.adam.urls')),
)

#
# MarkItUpFieldでPreviewを行うためのビュー定義
#
def apply_filter(request):
    from django.shortcuts import render_to_response
    from django.template import RequestContext
    from utils.markups import markdown
    markup = markdown(request.POST.get('data', ''))
    return render_to_response('preview.html', {'markup': markup}, RequestContext(request))
urlpatterns += patterns('',
    (r'^preview/',      apply_filter,   {}, 'preview'),
)
from django.conf import settings
if settings.DEBUG:
    #
    # プロダクトの静的ファイルの提供はApatchなどで行う
    #    Ref. http://djangoproject.jp/doc/ja/1.0/howto/static-files.html
    #
    import os.path
    document_root = lambda x: os.path.join(os.path.dirname(__file__), x)
    urlpatterns += patterns('django.views.static',
        (r'^favicon.ico$',              'serve', {'document_root': document_root('../../statics'), 'path': 'favicon.ico'}),
        (r'^apple-touch-icon.png$',     'serve', {'document_root': document_root('../../statics'), 'path': 'apple-touch-icon.png'}),
        (r'^css/(?P<path>.*)$',         'serve', {'document_root': document_root('../../statics/css')}),
        (r'^javascript/(?P<path>.*)$',  'serve', {'document_root': document_root('../../statics/javascript')}),
        (r'^image/(?P<path>.*)$',       'serve', {'document_root': document_root('../../statics/image')}),
        (r'^storage/(?P<path>.*)$',     'serve', {'document_root': document_root('../../statics/storage')}),
        (r'^component/(?P<path>.*)$',   'serve', {'document_root': document_root('../../statics/component')}),
        (r'^flatpages/(?P<path>.*)$',   'serve', {'document_root': document_root('../../statics/flatpages')}),
    )

src/kawaz/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls'), name='admin_doc'),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^registration/', include('registration.urls')),
    # core
    url(r'^members/', include('kawaz.core.profiles.urls')),
    # api
    url(r'^api/profiles/', include('kawaz.core.profiles.api.urls')),
)

src/Kawaz/contact/forms.py
# -*- coding: utf-8 -*-
#
# Author:        alisue
# Date:            2010/12/13
#
import re
from django import forms
from django.core.exceptions import ValidationError

from ..markitupfield.widgets import MarkItUpTextarea

JAPANESE_PATTERN = u'[一-龠ァ-ヶーぁ-んｱ-ﾝﾞﾟ]+'

class EmailForm(forms.Form):
    sender      = forms.EmailField(label=u"送信者のメールアドレス",
                                   help_text=u"返信時にこのメールアドレス宛にメールを送信するので普段ご利用のメールアドレスを入力してください")
    subject     = forms.CharField(label=u"題名", max_length=250,
                                  help_text=u"件名のみで要件がわかるように書いてください")
    body        = forms.CharField(label=u"本文", widget=MarkItUpTextarea,
                                 help_text=u"メールの本文です。HTML形式ではなくMarkdown形式で送信されるのでご注意ください")

    def is_valid(self):
        result = super(EmailForm, self).is_valid()
        cleaned_data = getattr(self, 'cleaned_data', None)
        if not result or not cleaned_data: return False
        body = cleaned_data.get("body", None)
        if body and not re.search(JAPANESE_PATTERN, body, re.U): # SPAM防止のため、一切日本語が含まれていない書き込みはrejectする
            raise ValidationError(u'日本語が含まれていないお問い合わせは送信することができません')
        return result

templates/index/anonymous.html
{% extends "base.html" %}
{% load projects %}

{% block action %}
<h3>ログイン</h3>
<form action="{% url auth_login %}" method="post" class="uniForm">{% csrf_token %}
    <label for="id_username">ユーザー名:</label> <input type="text" id="id_username" name="username" maxlength="30" class="span-3" />
    <label for="id_password">パスワード:</label> <input type="password" id="id_password" name="password" class="span-3" />
    <input type="submit" value="ログイン" />
</form>
<small><a href="{% url registration_register %}">新規会員登録</a></small><br />
<small><a href="{% url auth_password_reset %}">パスワードを忘れた</a></small>
{% endblock %}

{% block content %}
<h2>旧"ゲーム製作者コミュニティin札幌"の皆様へ</h2>
お知らせ、およびご説明いたします。<br>
<li>旧「ゲーム製作者コミュニティin札幌」は「札幌ゲーム製作者コミュニティ”Kawaz”」に名称を変更しました。</li>
<li>それに合わせまして、旧ポータルサイト（　現在はこのページにリダイレクトされます→<a href="http://www.gccsap.com/">http://www.gccsap.com/</a>　）を稼動停止し、この新ポータルサイトに移行しました。</li>
<li>サイト移行の際、<b>アカウントを含めた旧ポータルサイトのすべての情報は、データベースの変更のため一切引き継がれておりません。</b></li>
<br>
つきましては、この新ポータルサイトへの登録は任意で申請していただくことになります。<br>
<b>今後も札幌でメンバーとともにゲーム製作に関わっていただける方は、
<a href="http://www.kawaz.org/about/">About us</a>や
<a href="http://www.kawaz.org/rules/">利用規約</a>をよくお読みになった上で、
是非とも<a href ="http://kawaz.org/accounts/register/">新規会員登録</a>をこちらから行ってください。</b><br>
<br>
末筆ですが、これからKawazに登録される方もされない方も、今まで「ゲーム製作者コミュニティin札幌」に参加していただけたことを<b>心から感謝申し上げます。</b><br>
<br>
geekdrums<br>
<br>
<h2>札幌ゲーム製作者コミュニティ"Kawaz"とは？</h2>
<p>Kawazは非常に大きな組織となってしまったためそれを一言で述べるのは不可能に近い。しかしながら有名なWikipediaにて概略を余すところなくまとめてあるのが
発見できたので以下に引用する。</p>
<blockquote>
    <p>カエル（蛙）とは、脊椎動物亜門・両生綱・カエル目（無尾目）に分類される動物の総称。古称としてかわず
    （旧かな表記では「かはづ」）などがある。成体の頭は三角形で、目は上に飛び出している。胴体は丸っこく、尾はない。</p>
    <p>後肢が特に発達しており、後肢でジャンプすることで、敵から逃げたり、エサを捕まえたりする。後肢の指の間に水掻きが発達するものが多く、
    これを使ってよく泳ぐ。ほとんどの種で肋骨がない前肢は人間の腕に似た形状をしているが、ジャンプからの着地の際に身体への衝撃を和らげるのが主な役目である。</p>
    <p>餌となる小動物に飛びついて両肢で押さえつけたり、冬眠などのために土砂を掘ったり、汚れ落としのために片肢で顔を拭いたりする動作も可能である。</p>
    <p>アオガエル科やアマガエル科などの樹上生活をする種の多くでは指先に吸盤が発達し、
    その補助で細い枝などに掴まることはできるが、人間やサルのように物を片肢ないし両肢で掴み取ることはできない。幼生は四肢がなく、
    ひれのついた尾をもつ。成体とはちがう姿をしていて、俗に「オタマジャクシ（お玉杓子）」と呼ばれる（食器のお玉杓子に似た形状から）。</p>
    <p>オタマジャクシはえら呼吸を行い、尾を使って泳ぐため、淡水中でないと生きることができない。オタマジャクシは変態することで、
    尾をもたず肺呼吸する、四肢をもった幼体（仔ガエル）となる。</p>
    <cite><a href="http://ja.wikipedia.org/wiki/%E3%82%AB%E3%82%A8%E3%83%AB">Wikipedia</a>より引用</cite>
</blockquote>
<p>このようにKawazとは札幌でゲーム製作活動を行う人を結ぶためのコミュニティである。
初心者の学生からすでに現場で活躍するプロまで幅広い層のメンバーが所属している。
また、当コミュニティから派生して作られた、<a href="http://namaz.netgamers.jp/">名古屋ゲーム製作者コミュニティ"Namaz"</a>も存在し、活動を開始している。</p>

<h2>活動内容</h2>
<p>Kawazでは主に以下のようなことを行う</p>
<ul>
    <del><li>焼肉が食べたいがひとりでは怖いのでみんなで食べる</li></del>
    <li>現在の活動については、上のメニューから
<a href="http://www.kawaz.org/projects/">Projects</a>や
<a href="http://www.kawaz.org/events/">Events</a>などをご確認ください。</li>
    <li>詳しくは<a href="http://www.kawaz.org/about/">About us</a>をご覧ください</li>

</ul>
{% endblock %}

templates/index/authenticated.html
{% extends "base.html" %}
{% load calls %}
{% load drafts %}
{% load events %}
{% load history %}
{% load projects %}
{% load typeimg %}
{% load tweets %}
{% load messages %}
{% load tasks %}
{% load bugwaz %}

{% block title %}マイページ{% endblock %}

{% block head %}
{% compressed_css "index-authenticated" %}
{% compressed_js "index-authenticated" %}
{% compressed_js "pagenator" %}
{% ifhsp 'auth.post_goforit' for user %}
<style type="text/css">
    #adam-post-goforit{
        width: 100%;
        background: #000000;
        margin: 0;
        padding: 0;
    }
    #adam-post-goforit img{
        margin: 0;
        padding: 0;
        border: none;
    }
    #adam-post-goforit-button-holder{
        width: 100%;
        background: url(/image/dopes/adam/accept-bg.png);
        margin: 0;
        padding: 0;
    }
    #adam-post-goforit-accept-button{
        display: block;
        width: 320px;
        margin: 0 auto;
        background: #000000;
    }
    #adam-post-goforit-accept-button button{
        display: block;
        width: 171px;
        height: 96px;
        margin: 0 auto;
        padding: 0;
        border: none;
        cursor: pointer;
        background: url(/image/dopes/adam/accept.png);
    }
    #adam-post-goforit-accept-button button:hover{
        background: url(/image/dopes/adam/accept-hover.png);
    }
</style>
<script type="text/javascript">
  $(document).ready(function(){
      var current = location.href;
      var $adamButton = $('button.adam-post-goforit');
      $adamButton.click(function(){
        $.post("{% reverse "adam-post-goforit" %}");
          location.href = current;
          return false;
        });
  });
</script>
{% endifhsp %}

{% endblock %}

{% block summary %}
{% with user.get_profile as profile %}
{% include "profiles/components/overview-summary.html" %}
{% endwith %}
{% endblock %}

{% block action %}
{% get_progress_task_list request for user as task_list %}
{% if task_list %}
<h3>タスク</h3>
<ul class="ilist">
	{% for task in task_list|slice:":3" %}
	<li class="tasks-task-status-{{ task.status }}">
		<a href="{{ task.get_absolute_url }}">{{ task.title }}</a>
		<table>
			<tr>
				<th>重要度</th>
				<td>{{ task.get_priority_display }}</td>
			</tr>
			<tr>
				<th>締切り</th>
				<td>{{ task.deadline|date:"Y/m/d"|default:"未設定" }}</td>
			</tr>
		</table>
	</li>
	{% endfor %}
</ul>
{% if task_list|length > 3 %}
<p class="more"><a href="{% reverse 'tasks-task-list' %}">もっと見る</a></p>
{% endif %}
{% endif %}

<h3>新しく作る</h3>
<ul class="ilist">
	{% ifhsp 'blogs.add_entry' for user %}
	<li class="blogs-entry-create"><a href="{% reverse 'blogs-entry-create' user %}">ブログを書く</a></li>
	{% endifhsp %}
	{% ifhsp 'threads.add_thread' for user %}
	<li class="threads-thread-create"><a href="{% reverse 'threads-thread-create' %}">スレッドを立てる</a></li>
	{% endifhsp %}
	{% ifhsp 'events.add_event' for user %}
	<li class="events-event-create"><a href="{% reverse 'events-event-create' %}">イベントを企画</a></li>
	{% endifhsp %}
	{% ifhsp 'projects.add_project' for user %}
	<li class="projects-project-create"><a href="{% reverse 'projects-project-create' %}">プロジェクトを発足</a></li>
	{% endifhsp %}
	{% ifhsp 'commons.add_material' for user %}
	<li class="commons-material-create"><a href="{% reverse 'commons-material-create' %}">素材を投稿</a></li>
	{% endifhsp %}
	{% ifhsp 'messages.add_message' for user %}
	<li class="messages-message-create"><a href="{% reverse 'messages-message-create' %}">メッセージを送る</a></li>
	{% endifhsp %}
</ul>

<h3>自分の情報を見る</h3>
<ul class="ilist">
	<li class="profiles-profile-detail"><a href="{% reverse 'profiles-profile-detail' user %}">プロフィール</a></li>
	{% ifhsp 'messages.view_message' for user %}
	{% get_unread_message_count for user as unread_message_count %}
	<li class="messages-message-list"><a href="{% reverse 'messages-message-recived' %}">受信トレイ{% if unread_message_count %}({{ unread_message_count }}){% endif %}</a></li>
	{% endifhsp %}
	{% get_unaccepted_task_count request for user as unaccepted_task_count %}
	<li class="tasks-task-list"><a href="{% reverse 'tasks-task-list' %}">タスク一覧{% if unaccepted_task_count %}({{ unaccepted_task_count }}){% endif %}</a></li>
	<li class="blogs-entry-list"><a href="{% reverse 'blogs-entry-list' user %}">ブログ</a></li>
	{% get_drafts_count request as drafts_count %}
	<li class="drafts-draft-list"><a href="{% reverse 'drafts-draft-list' %}">下書き{% if drafts_count %}({{ drafts_count }}){% endif %}</a></li>
</ul>

<h3>設定を変える</h3>
<ul class="ilist">
	<li class="profiles-profile-update"><a href="{% reverse 'profiles-profile-update' %}">プロフィールを更新</a></li>
	<li class="auth-password-update"><a href="{% reverse 'auth_password_change' %}">パスワードを変更</a></li>
	<li class="auth-password-reset"><a href="{% reverse 'auth_password_reset' %}">パスワードをリセット</a></li>
</ul>

{% get_projects request for user as projects %}
{% if projects.count > 0 %}
{% for project in projects %}
<h3 class="projects-project-detail"><a href="{{ project.get_absolute_url }}">{{ project.title|truncateletters:8 }}</a></h3>
<ul class="ilist">
	<li class="wikis-entry-list"><a href="{% url wikis-entry-detail project.slug %}">ウィキトップ</a></li>
	{% get_active_task_count request for project as active_task_count %}
	<li class="tasks-task-list"><a href="{% url tasks-task-list project.slug %}">タスク一覧{% if active_task_count %}({{ active_task_count }}){% endif %}</a></li>
	<li class="commons-material-list"><a href="{% reverse 'commons-material-list' project=project.slug %}">素材一覧</a></li>
	{% get_active_report_count for project.bugwaz as active_report_count %}
	<li class="bugwaz-report-list"><a href="{{ project.bugwaz.get_absolute_url }}">Bugwaz{% if active_report_count %}({{ active_report_count }}){% endif %}</a></li>
</ul>
{% endfor %}
{% endif %}
{% endblock %}

{% block content %}
{% if 'MSIE' in request.META.HTTP_USER_AGENT %}
<div class="do-not-use-bloody-stupid-browser">
	<h2><strong>非常に大切なお知らせ</strong></h2>
	<p><strong>あなたがご利用のインターネットエクソプローラー（Sleipnirも含む）はセキュリティリスク・バグ・速度的問題など多数の問題を抱えています。</strong>
	Kawazがこのインターネットエクソプローラーに対応するためにはKawaz自体の重要な機能を排除する必要があるため、インターネットエクソプローラー
	への対応は行っておりません。したがって<strong>この機会にブラウザを他のものに変えることを強くおすすめいたします。</strong></p>
	<h3>おすすめブラウザ一覧</h3>
	<dl>
		<dt><a href="http://www.google.co.jp/chrome/intl/ja/landing_ch_yt.html?hl=ja&brand=CHMA&utm_campaign=ja&utm_source=ja-ha-apac-jp-bk&utm_medium=ha&utm_term=chrome">
			Google Chrome</a></dt>
		<dd>
			このブラウザに乗り換えるだけで様々なWebサイトの表示が早くなります。有名なGoogleが開発したブラウザです。
		</dd>
		<dt><a href="http://mozilla.jp/firefox/">Mozilla Firefox</a></dt>
		<dd>
			拡張機能をインストールすることで様々な便利機能を使うことができます。上級者におすすめです。
		</dd>
	</dl>
</div>
{% endif %}

{% get_calls for user as calls %}
{% if calls %}
<div id="calls">
	<h2 id="calls">おしらせ({{ calls.count }}件)</h2>
	<ul class="ilist">
		{% for call in calls %}
		<li class="manual">{% render_ctimg for call.content_type %}{{ call.get_message }}</li>
		{% endfor %}
	</ul>
	{#{% if calls.count > 3 %}#}
	<p class="more"><a href="{% reverse 'calls-call-clear' %}" class="postlink"
		confirm_message="本当にすべてのお知らせを既読にしてもよろしいですか？"
		success_message="すべてのお知らせを既読にしました">すべてのお知らせを既読にする</a></p>
	{#{% endif %}#}
</div><!-- /calls -->
{% endif %}

<h2 id="history">更新情報</h2>
{% get_history_timelines as timelines %}
<table class="timelines">
{% for timeline in timelines|slice:":10" %}
	<tr>
		{% include "history/components/list-item.html" %}
	</tr>
{% empty %}
	<tr><td colspan="2">更新情報はありません</td>
{% endfor %}
</table>
<p class="more"><a href="{% reverse 'history-timeline-list' %}">もっと見る</a></p>

{% ifhsp 'auth.post_goforit' for user %}
<div id="adam-post-goforit">
    <img src="{{ MEDIA_URL }}image/dopes/adam/adam-post-goforit.jpg" />
    <div id="adam-post-goforit-button-holder">
        <div id="adam-post-goforit-accept-button">
            <button type="button" class="adam-post-goforit"></button>
        </div>
    </div>
</div>
{% endifhsp %}

<h2 id="tweets">かわずったー</h2>
{% ifhsp 'tweets.add_tweet' for user %}
<form id="tweet-form" action="{% url tweets-tweet-create %}" method="post">{% csrf_token %}
	<p><input type="hidden" id="id_reply" name="reply"></p>
	<p><input type="hidden" id="id_source" name="source" value="kawaz"></p>
	<p><textarea id="id_body" name="body" title="いまなにしてるの？" rows="1" cols="20"></textarea></p>
	<p><input type="submit" id="tweet-submit" value="つぶやく" /></p>
</form>
{% endifhsp %}
{% get_tweets as tweets %}
<ul class="tweets">
	{% for tweet in tweets|slice:":6" %}
	<li class="tweet{% if user in tweet.users.all %} tweet-favorite{% endif %}" id="tweet-{{ tweet.pk }}">
		{% include "tweets/components/list-item.html" %}
	</li>
	{% empty %}
	<li class="tweet empty">まだ誰もつぶやいていません</li>
	{% endfor %}
</ul>
{% if tweets|length >= 6 %}
<p class="more tweet-more"><a href="{% reverse 'tweets-tweet-list' %}">もっと読む</a></p>
{% endif %}
{% if not user.get_profile.twitter_token %}
<p class="twitter-auth twitter"><a href="{% reverse 'twitter_oauth_auth' %}">twitter連携を有効にする</a></p>
{% else %}
<p class="tips">Twitterで#Kawazをつけて呟くと、かわずったーに反映させることができます</p>
{% endif %}

<h2 id="events">参加中のイベント</h2>
{% get_events request for user as events %}
<ul class="events">
	{% for event in events %}
	<li class="event">
		{% include "events/components/list-item.html" %}
	</li>
	{% empty %}
	<li class="event empty">現在参加しているイベントはありません</li>
	{% endfor %}
</ul>

<h2 id="projects">参加中のプロジェクト</h2>
{% get_projects request for user as projects %}
<ul class="projects">
	{% for project in projects %}
	<li class="project">
		{% include "projects/components/list-item.html" %}
	</li>
	{% empty %}
	<li class="project empty">現在参加しているプロジェクトはありません</li>
	{% endfor %}
</ul>
{% endblock %}